# Generated by Django 5.2.8 on 2025-11-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_stream_app', '0003_movie_backdrop_path_movie_poster_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('seasons_count', models.IntegerField(default=0)),
                ('episodes_count', models.IntegerField(default=0)),
                ('overall_rating', models.FloatField(default=0)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='series_posters/')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='series_backdrops/')),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('content_type', models.CharField(default='series', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
