# Generated by Django 5.2.8 on 2025-11-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_stream_app', '0004_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
