# Generated by Django 5.2.8 on 2025-11-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_stream_app', '0005_series_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='poster_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
