# Generated by Django 5.2.8 on 2025-11-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_stream_app', '0006_series_backdrop_path_series_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, default=2020, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='first_air_date',
            field=models.PositiveIntegerField(blank=True, default=2020, null=True),
        ),
    ]
