# Generated by Django 5.2.8 on 2025-11-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_stream_app', '0007_alter_movie_release_year_alter_series_first_air_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='series', to='cinema_stream_app.genre'),
        ),
    ]
