# Generated by Django 5.2.7 on 2025-11-25 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_stream_app', '0011_alter_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cinema_stream_app.series'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cinema_stream_app.movie'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'movie'), ('user', 'series')},
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
